version: "2"
services:
  ui:
    container_name: ui
    build: ./ui
    ports:
      - "80:80"
    depends_on: 
      - api
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - "8080:8080"
    depends_on: 
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

